package view;

public class About extends javax.swing.JFrame {
    
    public About() {
        initComponents();
        
        setAbout();
    }
    
    public void setAbout() {
        txtAbout.setText("<b>JPasswords</b> is an open source application and is licensed under GNU General Public License v3.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        softwarePanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        aboutPanel = new javax.swing.JPanel();
        aboutScroll = new javax.swing.JScrollPane();
        txtAbout = new javax.swing.JTextPane();
        creditsPanel = new javax.swing.JPanel();
        creditsScroll = new javax.swing.JScrollPane();
        txtCredits = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de");
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("frmAbout"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        softwarePanel.setMaximumSize(new java.awt.Dimension(400, 300));
        softwarePanel.setMinimumSize(new java.awt.Dimension(400, 300));
        softwarePanel.setName("softwarePanel"); // NOI18N
        softwarePanel.setPreferredSize(new java.awt.Dimension(400, 300));
        softwarePanel.setLayout(new java.awt.BorderLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setMaximumSize(new java.awt.Dimension(400, 300));
        lblLogo.setMinimumSize(new java.awt.Dimension(400, 300));
        lblLogo.setName("lblLogo"); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(400, 300));
        softwarePanel.add(lblLogo, java.awt.BorderLayout.CENTER);

        getContentPane().add(softwarePanel, java.awt.BorderLayout.CENTER);

        tabbedPane.setName("tabbedPane"); // NOI18N

        aboutPanel.setMaximumSize(new java.awt.Dimension(400, 100));
        aboutPanel.setMinimumSize(new java.awt.Dimension(400, 100));
        aboutPanel.setName("aboutPanel"); // NOI18N
        aboutPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        aboutPanel.setLayout(new java.awt.BorderLayout());

        aboutScroll.setName("aboutScroll"); // NOI18N

        txtAbout.setName("txtAbout"); // NOI18N
        aboutScroll.setViewportView(txtAbout);

        aboutPanel.add(aboutScroll, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Acerca de", aboutPanel);

        creditsPanel.setMaximumSize(new java.awt.Dimension(400, 100));
        creditsPanel.setMinimumSize(new java.awt.Dimension(400, 100));
        creditsPanel.setName("creditsPanel"); // NOI18N
        creditsPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        creditsPanel.setLayout(new java.awt.BorderLayout());

        creditsScroll.setName("creditsScroll"); // NOI18N

        txtCredits.setName("txtCredits"); // NOI18N
        creditsScroll.setViewportView(txtCredits);

        creditsPanel.add(creditsScroll, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Créditos", creditsPanel);

        getContentPane().add(tabbedPane, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JScrollPane aboutScroll;
    private javax.swing.JPanel creditsPanel;
    private javax.swing.JScrollPane creditsScroll;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel softwarePanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextPane txtAbout;
    private javax.swing.JTextPane txtCredits;
    // End of variables declaration//GEN-END:variables
}
