/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Recepcion03
 */
public class Login extends javax.swing.JFrame {

    private String usuario;
    private String clave;
    
    /**
     * Creates new form Login
     */
    public Login() {
        this.usuario = "administrador";
        this.clave = "admin";                
        
        initComponents();
                
        //ImageIcon iconLogo = new ImageIcon("img/logo_holiwallet_small.png");                               
        //lblImagen.setIcon(iconLogo);
        
        //lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("logo_holiwallet_small.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelFormulario = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnInicio = new javax.swing.JButton();
        panelAyuda = new javax.swing.JPanel();
        btnAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Holiwallet");
        setLocationByPlatform(true);
        setName("frmLogin"); // NOI18N

        panelFormulario.setName("panelFormulario"); // NOI18N
        java.awt.GridBagLayout panelFormularioLayout = new java.awt.GridBagLayout();
        panelFormularioLayout.columnWidths = new int[] {0};
        panelFormularioLayout.rowHeights = new int[] {0};
        panelFormularioLayout.columnWeights = new double[] {0.0};
        panelFormularioLayout.rowWeights = new double[] {0.0};
        panelFormulario.setLayout(panelFormularioLayout);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/logo_holiwallet_small.png"))); // NOI18N
        lblLogo.setName("lblLogo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelFormulario.add(lblLogo, gridBagConstraints);

        lblUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuario:");
        lblUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUsuario.setName("lblUsuario"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        panelFormulario.add(lblUsuario, gridBagConstraints);

        txtUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setToolTipText("Introduce tu nombre de usuario.");
        txtUsuario.setMinimumSize(new java.awt.Dimension(250, 30));
        txtUsuario.setName("txtUsuario"); // NOI18N
        txtUsuario.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        panelFormulario.add(txtUsuario, gridBagConstraints);

        lblClave.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblClave.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClave.setText("Clave:");
        lblClave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblClave.setName("lblClave"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        panelFormulario.add(lblClave, gridBagConstraints);

        txtClave.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtClave.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtClave.setToolTipText("Introduce tu clave.");
        txtClave.setMinimumSize(new java.awt.Dimension(250, 30));
        txtClave.setName("txtClave"); // NOI18N
        txtClave.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        panelFormulario.add(txtClave, gridBagConstraints);

        btnInicio.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnInicio.setText("Iniciar sesión");
        btnInicio.setToolTipText("Iniciar sesión");
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setName("btnInicio"); // NOI18N
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        panelFormulario.add(btnInicio, gridBagConstraints);

        getContentPane().add(panelFormulario, java.awt.BorderLayout.CENTER);

        panelAyuda.setName("panelAyuda"); // NOI18N
        panelAyuda.setLayout(new java.awt.BorderLayout());

        btnAyuda.setText("[ ? ]");
        btnAyuda.setToolTipText("¿Olvidaste tu contraseña?");
        btnAyuda.setName("btnAyuda"); // NOI18N
        panelAyuda.add(btnAyuda, java.awt.BorderLayout.EAST);

        getContentPane().add(panelAyuda, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        String miUsuario = txtUsuario.getText();
        char[] caracteres = txtClave.getPassword();
        String miClave = "";
        
        for(char letra : caracteres){
            miClave = miClave + letra;
        }                
        
        if(miUsuario.equals(usuario) && miClave.equals(clave)){
            JOptionPane.showMessageDialog(null, "Bienvenido " + miUsuario);
        }
        else {
            JOptionPane.showMessageDialog(null, "Usuario o clave incorrecta");
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelAyuda;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
