package over.view;

import over.controller.*;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

import over.model.pojo.Privilege;
import over.model.pojo.User;

public class Dashboard extends javax.swing.JFrame {
    private final CardLayout cardLayout;    
    private final Image backgroundImage;
    private List<Component> componentList;
    private Controller controller;
    private User user;

    public Dashboard(User user) {
        this.user = user;
        BackgroundImage.setName("dashboard_white_blue01.jpg");
        backgroundImage = BackgroundImage.request();
        
        initComponents();
        setDashboard();
        
        cardLayout = (CardLayout)(mainPanel.getLayout());
    }

    public void setDashboard() {
        switch (new Privilege().getPrivilege(user)) {
            case "Supervisor": break;
            case "Administrador": administratorUser(); break;
            case "Estándar": standardUser(); break;
            default: break;
        }
    }

    public void administratorUser() {
        /*lblCredentialsLogo.setVisible(true);
        lblAccessLogo.setVisible(true);
        lblDepartmentsLogo.setVisible(true);
        lblEmployees.setVisible(true);*/
        lblHierarchyLogo.setVisible(false);
        /*lblKindProductLogo.setVisible(true);
        lblPrivilegesLogo.setVisible(true);
        lblProductLogo.setVisible(true);*/
    }

    public void standardUser() {
        /*lblCredentialsLogo.setVisible(true);
        lblAccessLogo.setVisible(true);*/
        lblDepartmentsLogo.setVisible(false);
        lblEmployees.setVisible(false);
        lblHierarchyLogo.setVisible(false);
        lblKindProductLogo.setVisible(false);
        lblPrivilegesLogo.setVisible(false);
        lblProductLogo.setVisible(false);
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolBar = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        separator = new javax.swing.JToolBar.Separator();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(backgroundImage, 0, 0, null);
            }
        };
        dashboardPanel = new javax.swing.JPanel();
        lblKindProductLogo = new javax.swing.JLabel();
        lblProductLogo = new javax.swing.JLabel();
        lblCredentialsLogo = new javax.swing.JLabel();
        lblEmployees = new javax.swing.JLabel();
        lblDepartmentsLogo = new javax.swing.JLabel();
        lblHierarchyLogo = new javax.swing.JLabel();
        lblPrivilegesLogo = new javax.swing.JLabel();
        lblAccessLogo = new javax.swing.JLabel();
        kindProductsPanel = new javax.swing.JPanel();
        productsFiller1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        kindProductPanel = new javax.swing.JPanel();
        lblKindProduct = new javax.swing.JLabel();
        txtKindProduct = new javax.swing.JTextField();
        btnAddKindProduct = new javax.swing.JButton();
        productsFiller2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        existingKindProductsPanel = new javax.swing.JPanel();
        existingKindProductsScroll = new javax.swing.JScrollPane();
        existingKindProductsList = new javax.swing.JList<>();
        btnModifyKindProduct = new javax.swing.JButton();
        btnDeleteKindProduct = new javax.swing.JButton();
        productsFiller3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        productsPanel = new javax.swing.JPanel();
        productFiller1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        productPanel = new javax.swing.JPanel();
        lblProduct = new javax.swing.JLabel();
        txtProduct = new javax.swing.JTextField();
        lblKind = new javax.swing.JLabel();
        cmbKindProduct = new javax.swing.JComboBox<>();
        btnAddProduct = new javax.swing.JButton();
        productFiller2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        existingProductsPanel = new javax.swing.JPanel();
        existingProductsScroll = new javax.swing.JScrollPane();
        existingProductsTable = new javax.swing.JTable();
        btnModifyProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        productFiller3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        credentialsPanel = new javax.swing.JPanel();
        exployeesPanel = new javax.swing.JPanel();
        departmentsPanel = new javax.swing.JPanel();
        departmentsFiller1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        departmentPanel = new javax.swing.JPanel();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        btnAddDepartment = new javax.swing.JButton();
        departmentsFiller2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        existingDepartmentsPanel = new javax.swing.JPanel();
        existingDepartmentsScroll = new javax.swing.JScrollPane();
        existingDepartmentsList = new javax.swing.JList<>();
        btnModifyDepartment = new javax.swing.JButton();
        btnDeleteDepartment = new javax.swing.JButton();
        departmentsFiller3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        hierarchiesPanel = new javax.swing.JPanel();
        hierarchiesFiller1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        hierarchyPanel = new javax.swing.JPanel();
        lblHierarchy = new javax.swing.JLabel();
        txtHierarchy = new javax.swing.JTextField();
        btnHierarchy = new javax.swing.JButton();
        hierarchiesFiller2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        existingHierarchiesPanel = new javax.swing.JPanel();
        existingHierarchiesScroll = new javax.swing.JScrollPane();
        existingHierarchiesTable = new javax.swing.JTable();
        btnModifyHierarchy = new javax.swing.JButton();
        btnDeleteHierarchy = new javax.swing.JButton();
        hierarchiesFiller3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        privilegesPanel = new javax.swing.JPanel();
        privilegesFiller1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        privilegePanel = new javax.swing.JPanel();
        lblPrivilege = new javax.swing.JLabel();
        txtPrivilege = new javax.swing.JTextField();
        btnAddPrivilege = new javax.swing.JButton();
        privilegesFiller2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        existingPrivilegesPanel = new javax.swing.JPanel();
        existingPrivilegesScroll = new javax.swing.JScrollPane();
        existingPrivilegesList = new javax.swing.JList<>();
        btnModifyPrivilege = new javax.swing.JButton();
        btnDeletePrivilege = new javax.swing.JButton();
        kindProductsCheck = new javax.swing.JCheckBox();
        departmentsCheck = new javax.swing.JCheckBox();
        productsCheck = new javax.swing.JCheckBox();
        employeesCheck = new javax.swing.JCheckBox();
        hierarchiesCheck = new javax.swing.JCheckBox();
        privilegesCheck = new javax.swing.JCheckBox();
        credentialsCheck = new javax.swing.JCheckBox();
        accessesCheck = new javax.swing.JCheckBox();
        privilegesFiller3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 32767));
        accessesPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exportItem = new javax.swing.JMenuItem();
        printItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Holiwallet v0.1 - Dashboard");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frmDashboard"); // NOI18N

        toolBar.setRollover(true);
        toolBar.setName("toolBar"); // NOI18N

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/toolbar/home.png"))); // NOI18N
        btnHome.setToolTipText("Inicio");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setName("btnHome"); // NOI18N
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        toolBar.add(btnHome);

        separator.setName("separator"); // NOI18N
        toolBar.add(separator);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/toolbar/back.png"))); // NOI18N
        btnBack.setToolTipText("Atras");
        btnBack.setFocusable(false);
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.setName("btnBack"); // NOI18N
        btnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        toolBar.add(btnBack);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/toolbar/next.png"))); // NOI18N
        btnNext.setToolTipText("Adelante");
        btnNext.setFocusable(false);
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.setName("btnNext"); // NOI18N
        btnNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        toolBar.add(btnNext);

        getContentPane().add(toolBar, java.awt.BorderLayout.NORTH);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        dashboardPanel.setName("dashboardPanel"); // NOI18N
        dashboardPanel.setOpaque(false);
        dashboardPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        dashboardPanel.setLayout(new java.awt.GridBagLayout());

        lblKindProductLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/dashboard/kind_of_product.png"))); // NOI18N
        lblKindProductLogo.setText("Tipo de productos");
        lblKindProductLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblKindProductLogo.setName("lblKindProductLogo"); // NOI18N
        lblKindProductLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblKindProductLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKindProductLogoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        dashboardPanel.add(lblKindProductLogo, gridBagConstraints);

        lblProductLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/dashboard/products.png"))); // NOI18N
        lblProductLogo.setText("Productos");
        lblProductLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProductLogo.setName("lblProductLogo"); // NOI18N
        lblProductLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblProductLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductLogoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        dashboardPanel.add(lblProductLogo, gridBagConstraints);

        lblCredentialsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/dashboard/credentials.png"))); // NOI18N
        lblCredentialsLogo.setText("Credenciales");
        lblCredentialsLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCredentialsLogo.setName("lblCredentialsLogo"); // NOI18N
        lblCredentialsLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCredentialsLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCredentialsLogoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        dashboardPanel.add(lblCredentialsLogo, gridBagConstraints);

        lblEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/dashboard/users.png"))); // NOI18N
        lblEmployees.setText("Empleados");
        lblEmployees.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEmployees.setName("lblEmployees"); // NOI18N
        lblEmployees.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeesMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        dashboardPanel.add(lblEmployees, gridBagConstraints);

        lblDepartmentsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/dashboard/departments.png"))); // NOI18N
        lblDepartmentsLogo.setText("Departamentos");
        lblDepartmentsLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDepartmentsLogo.setName("lblDepartmentsLogo"); // NOI18N
        lblDepartmentsLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblDepartmentsLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDepartmentsLogoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        dashboardPanel.add(lblDepartmentsLogo, gridBagConstraints);

        lblHierarchyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/dashboard/hierarchy.png"))); // NOI18N
        lblHierarchyLogo.setText("Jerarquías");
        lblHierarchyLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHierarchyLogo.setName("lblHierarchyLogo"); // NOI18N
        lblHierarchyLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblHierarchyLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHierarchyLogoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        dashboardPanel.add(lblHierarchyLogo, gridBagConstraints);

        lblPrivilegesLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/dashboard/privileges.png"))); // NOI18N
        lblPrivilegesLogo.setText("Privilegios");
        lblPrivilegesLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPrivilegesLogo.setName("lblPrivilegesLogo"); // NOI18N
        lblPrivilegesLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblPrivilegesLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrivilegesLogoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        dashboardPanel.add(lblPrivilegesLogo, gridBagConstraints);

        lblAccessLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccessLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/dashboard/access.png"))); // NOI18N
        lblAccessLogo.setText("Accesos");
        lblAccessLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAccessLogo.setName("lblAccessLogo"); // NOI18N
        lblAccessLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblAccessLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccessLogoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        dashboardPanel.add(lblAccessLogo, gridBagConstraints);

        mainPanel.add(dashboardPanel, "dashboardPanel");

        kindProductsPanel.setBackground(new java.awt.Color(255, 255, 255));
        kindProductsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipos de productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        kindProductsPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        kindProductsPanel.setName("kindProductsPanel"); // NOI18N
        kindProductsPanel.setOpaque(false);
        kindProductsPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        kindProductsPanel.setLayout(new javax.swing.BoxLayout(kindProductsPanel, javax.swing.BoxLayout.Y_AXIS));

        productsFiller1.setName("productsFiller1"); // NOI18N
        kindProductsPanel.add(productsFiller1);

        kindProductPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar tipo de producto"));
        kindProductPanel.setMinimumSize(new java.awt.Dimension(300, 60));
        kindProductPanel.setName("kindProductPanel"); // NOI18N
        kindProductPanel.setOpaque(false);
        kindProductPanel.setPreferredSize(new java.awt.Dimension(300, 60));

        lblKindProduct.setText("Nombre");
        lblKindProduct.setName("lblKindProduct"); // NOI18N
        kindProductPanel.add(lblKindProduct);

        txtKindProduct.setMinimumSize(new java.awt.Dimension(200, 30));
        txtKindProduct.setName("txtKindProduct"); // NOI18N
        txtKindProduct.setPreferredSize(new java.awt.Dimension(200, 30));
        txtKindProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKindProductKeyPressed(evt);
            }
        });
        kindProductPanel.add(txtKindProduct);

        btnAddKindProduct.setText("Agregar");
        btnAddKindProduct.setName("btnAddKindProduct"); // NOI18N
        btnAddKindProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddKindProductMouseClicked(evt);
            }
        });
        btnAddKindProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKindProductKeyPressed(evt);
            }
        });
        kindProductPanel.add(btnAddKindProduct);

        kindProductsPanel.add(kindProductPanel);

        productsFiller2.setName("productsFiller2"); // NOI18N
        kindProductsPanel.add(productsFiller2);

        existingKindProductsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de productos existentes"));
        existingKindProductsPanel.setName("existingKindProductsPanel"); // NOI18N
        existingKindProductsPanel.setOpaque(false);
        existingKindProductsPanel.setPreferredSize(new java.awt.Dimension(300, 180));
        existingKindProductsPanel.setLayout(new java.awt.GridBagLayout());

        existingKindProductsScroll.setMinimumSize(new java.awt.Dimension(319, 162));
        existingKindProductsScroll.setName("existingKindProductsScroll"); // NOI18N

        existingKindProductsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        existingKindProductsList.setMaximumSize(new java.awt.Dimension(300, 300));
        existingKindProductsList.setMinimumSize(new java.awt.Dimension(300, 300));
        existingKindProductsList.setName("existingKindProductsList"); // NOI18N
        existingKindProductsList.setPreferredSize(new java.awt.Dimension(300, 300));
        existingKindProductsList.setVisibleRowCount(10);
        existingKindProductsList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                existingKindProductsListKeyPressed(evt);
            }
        });
        existingKindProductsScroll.setViewportView(existingKindProductsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingKindProductsPanel.add(existingKindProductsScroll, gridBagConstraints);

        btnModifyKindProduct.setText("Modificar");
        btnModifyKindProduct.setName("btnModifyKindProduct"); // NOI18N
        btnModifyKindProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyKindProductMouseClicked(evt);
            }
        });
        btnModifyKindProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnModifyKindProductKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingKindProductsPanel.add(btnModifyKindProduct, gridBagConstraints);

        btnDeleteKindProduct.setText("Eliminar");
        btnDeleteKindProduct.setName("btnDeleteKindProduct"); // NOI18N
        btnDeleteKindProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteKindProductMouseClicked(evt);
            }
        });
        btnDeleteKindProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeleteKindProductKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingKindProductsPanel.add(btnDeleteKindProduct, gridBagConstraints);

        kindProductsPanel.add(existingKindProductsPanel);

        productsFiller3.setName("productsFiller3"); // NOI18N
        kindProductsPanel.add(productsFiller3);

        mainPanel.add(kindProductsPanel, "kindProductsPanel");

        productsPanel.setBackground(new java.awt.Color(255, 255, 255));
        productsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        productsPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        productsPanel.setName("productsPanel"); // NOI18N
        productsPanel.setOpaque(false);
        productsPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        productsPanel.setLayout(new javax.swing.BoxLayout(productsPanel, javax.swing.BoxLayout.Y_AXIS));

        productFiller1.setName("productFiller1"); // NOI18N
        productsPanel.add(productFiller1);

        productPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar producto"));
        productPanel.setName("productPanel"); // NOI18N

        lblProduct.setText("Nombre");
        lblProduct.setName("lblProduct"); // NOI18N
        productPanel.add(lblProduct);

        txtProduct.setMinimumSize(new java.awt.Dimension(200, 30));
        txtProduct.setName("txtProduct"); // NOI18N
        txtProduct.setPreferredSize(new java.awt.Dimension(200, 30));
        productPanel.add(txtProduct);

        lblKind.setText("Tipo de producto");
        lblKind.setName("lblKind"); // NOI18N
        productPanel.add(lblKind);

        cmbKindProduct.setName("cmbKindProduct"); // NOI18N
        productPanel.add(cmbKindProduct);

        btnAddProduct.setText("Agregar");
        btnAddProduct.setName("btnAddProduct"); // NOI18N
        btnAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProductMouseClicked(evt);
            }
        });
        btnAddProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddProductKeyPressed(evt);
            }
        });
        productPanel.add(btnAddProduct);

        productsPanel.add(productPanel);

        productFiller2.setName("productFiller2"); // NOI18N
        productsPanel.add(productFiller2);

        existingProductsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos existentes"));
        existingProductsPanel.setName("existingProductsPanel"); // NOI18N
        existingProductsPanel.setLayout(new java.awt.GridBagLayout());

        existingProductsScroll.setName("existingProductsScroll"); // NOI18N

        existingProductsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Id", "Nombre", "Tipo"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        existingProductsTable.setFillsViewportHeight(true);
        existingProductsTable.setMaximumSize(new java.awt.Dimension(300, 300));
        existingProductsTable.setMinimumSize(new java.awt.Dimension(300, 300));
        existingProductsTable.setName("existingProductsTable"); // NOI18N
        existingProductsTable.setPreferredSize(new java.awt.Dimension(300, 300));
        existingProductsScroll.setViewportView(existingProductsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingProductsPanel.add(existingProductsScroll, gridBagConstraints);

        btnModifyProduct.setText("Modificar");
        btnModifyProduct.setName("btnModifyProduct"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingProductsPanel.add(btnModifyProduct, gridBagConstraints);

        btnDeleteProduct.setText("Eliminar");
        btnDeleteProduct.setName("btnDeleteProduct"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingProductsPanel.add(btnDeleteProduct, gridBagConstraints);

        productsPanel.add(existingProductsPanel);

        productFiller3.setName("productFiller3"); // NOI18N
        productsPanel.add(productFiller3);

        mainPanel.add(productsPanel, "productsPanel");

        credentialsPanel.setBackground(new java.awt.Color(255, 255, 255));
        credentialsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Credenciales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        credentialsPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        credentialsPanel.setName("credentialsPanel"); // NOI18N
        credentialsPanel.setOpaque(false);
        credentialsPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.add(credentialsPanel, "credentialsPanel");

        exployeesPanel.setBackground(new java.awt.Color(255, 255, 255));
        exployeesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        exployeesPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        exployeesPanel.setName("employeesPanel"); // NOI18N
        exployeesPanel.setOpaque(false);
        exployeesPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.add(exployeesPanel, "employeesPanel");

        departmentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        departmentsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Departamentos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        departmentsPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        departmentsPanel.setName("departmentsPanel"); // NOI18N
        departmentsPanel.setOpaque(false);
        departmentsPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        departmentsPanel.setLayout(new javax.swing.BoxLayout(departmentsPanel, javax.swing.BoxLayout.Y_AXIS));

        departmentsFiller1.setName("departmentsFiller1"); // NOI18N
        departmentsPanel.add(departmentsFiller1);

        departmentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar departamento"));
        departmentPanel.setMinimumSize(new java.awt.Dimension(300, 60));
        departmentPanel.setName("departmentPanel"); // NOI18N
        departmentPanel.setOpaque(false);
        departmentPanel.setPreferredSize(new java.awt.Dimension(300, 60));

        lblDepartment.setText("Nombre");
        lblDepartment.setName("lblDepartment"); // NOI18N
        departmentPanel.add(lblDepartment);

        txtDepartment.setMinimumSize(new java.awt.Dimension(200, 30));
        txtDepartment.setName("txtDepartment"); // NOI18N
        txtDepartment.setPreferredSize(new java.awt.Dimension(200, 30));
        departmentPanel.add(txtDepartment);

        btnAddDepartment.setText("Agregar");
        btnAddDepartment.setName("btnAddDepartment"); // NOI18N
        btnAddDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddDepartmentMouseClicked(evt);
            }
        });
        btnAddDepartment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddDepartmentKeyPressed(evt);
            }
        });
        departmentPanel.add(btnAddDepartment);

        departmentsPanel.add(departmentPanel);

        departmentsFiller2.setName("departmentsFiller2"); // NOI18N
        departmentsPanel.add(departmentsFiller2);

        existingDepartmentsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Departamentos existentes"));
        existingDepartmentsPanel.setName("existingDepartmentsPanel"); // NOI18N
        existingDepartmentsPanel.setOpaque(false);
        existingDepartmentsPanel.setPreferredSize(new java.awt.Dimension(300, 180));
        existingDepartmentsPanel.setLayout(new java.awt.GridBagLayout());

        existingDepartmentsScroll.setName("existingDepartmentsScroll"); // NOI18N

        existingDepartmentsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        existingDepartmentsList.setMaximumSize(new java.awt.Dimension(300, 300));
        existingDepartmentsList.setMinimumSize(new java.awt.Dimension(300, 300));
        existingDepartmentsList.setName("existingDepartmentsList"); // NOI18N
        existingDepartmentsList.setPreferredSize(new java.awt.Dimension(300, 300));
        existingDepartmentsList.setVisibleRowCount(10);
        existingDepartmentsScroll.setViewportView(existingDepartmentsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingDepartmentsPanel.add(existingDepartmentsScroll, gridBagConstraints);

        btnModifyDepartment.setText("Modificar");
        btnModifyDepartment.setName("btnModifyDepartment"); // NOI18N
        btnModifyDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyDepartmentMouseClicked(evt);
            }
        });
        btnModifyDepartment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnModifyDepartmentKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingDepartmentsPanel.add(btnModifyDepartment, gridBagConstraints);

        btnDeleteDepartment.setText("Eliminar");
        btnDeleteDepartment.setName("btnDeleteDepartment"); // NOI18N
        btnDeleteDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteDepartmentMouseClicked(evt);
            }
        });
        btnDeleteDepartment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeleteDepartmentKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingDepartmentsPanel.add(btnDeleteDepartment, gridBagConstraints);

        departmentsPanel.add(existingDepartmentsPanel);

        departmentsFiller3.setName("departmentsFiller3"); // NOI18N
        departmentsPanel.add(departmentsFiller3);

        mainPanel.add(departmentsPanel, "departmentsPanel");

        hierarchiesPanel.setBackground(new java.awt.Color(255, 255, 255));
        hierarchiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jerarquías", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        hierarchiesPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        hierarchiesPanel.setName("hierarchiesPanel"); // NOI18N
        hierarchiesPanel.setOpaque(false);
        hierarchiesPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        hierarchiesPanel.setLayout(new javax.swing.BoxLayout(hierarchiesPanel, javax.swing.BoxLayout.Y_AXIS));

        hierarchiesFiller1.setName("hierarchiesFiller1"); // NOI18N
        hierarchiesPanel.add(hierarchiesFiller1);

        hierarchyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar jerarquía", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        hierarchyPanel.setName("hierarchyPanel"); // NOI18N
        hierarchyPanel.setOpaque(false);

        lblHierarchy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHierarchy.setText("Nombre");
        lblHierarchy.setName("lblHierarchy"); // NOI18N
        hierarchyPanel.add(lblHierarchy);

        txtHierarchy.setName("txtHierarchy"); // NOI18N
        txtHierarchy.setPreferredSize(new java.awt.Dimension(300, 30));
        txtHierarchy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHierarchyKeyPressed(evt);
            }
        });
        hierarchyPanel.add(txtHierarchy);

        btnHierarchy.setText("Agregar");
        btnHierarchy.setName("btnHierarchy"); // NOI18N
        btnHierarchy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHierarchyMouseClicked(evt);
            }
        });
        btnHierarchy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHierarchyKeyPressed(evt);
            }
        });
        hierarchyPanel.add(btnHierarchy);

        hierarchiesPanel.add(hierarchyPanel);

        hierarchiesFiller2.setName("hierarchiesFiller2"); // NOI18N
        hierarchiesPanel.add(hierarchiesFiller2);

        existingHierarchiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jerarquías existentes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        existingHierarchiesPanel.setName("existingHierarchiesPanel"); // NOI18N
        existingHierarchiesPanel.setOpaque(false);
        existingHierarchiesPanel.setLayout(new java.awt.GridBagLayout());

        existingHierarchiesScroll.setMinimumSize(new java.awt.Dimension(300, 200));
        existingHierarchiesScroll.setName("existingHierarchiesScroll"); // NOI18N
        existingHierarchiesScroll.setPreferredSize(new java.awt.Dimension(300, 200));

        existingHierarchiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        existingHierarchiesTable.setFillsViewportHeight(true);
        existingHierarchiesTable.setMinimumSize(new java.awt.Dimension(300, 200));
        existingHierarchiesTable.setName("existingHierarchiesTable"); // NOI18N
        existingHierarchiesTable.setPreferredSize(new java.awt.Dimension(300, 200));
        existingHierarchiesScroll.setViewportView(existingHierarchiesTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingHierarchiesPanel.add(existingHierarchiesScroll, gridBagConstraints);

        btnModifyHierarchy.setText("Modificar");
        btnModifyHierarchy.setName("btnModifyHierarchy"); // NOI18N
        btnModifyHierarchy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyHierarchyMouseClicked(evt);
            }
        });
        btnModifyHierarchy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnModifyHierarchyKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingHierarchiesPanel.add(btnModifyHierarchy, gridBagConstraints);

        btnDeleteHierarchy.setText("Eliminar");
        btnDeleteHierarchy.setName("btnDeleteHierarchy"); // NOI18N
        btnDeleteHierarchy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteHierarchyMouseClicked(evt);
            }
        });
        btnDeleteHierarchy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeleteHierarchyKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingHierarchiesPanel.add(btnDeleteHierarchy, gridBagConstraints);

        hierarchiesPanel.add(existingHierarchiesPanel);

        hierarchiesFiller3.setName("hierarchiesFiller3"); // NOI18N
        hierarchiesPanel.add(hierarchiesFiller3);

        mainPanel.add(hierarchiesPanel, "hierarchiesPanel");

        privilegesPanel.setBackground(new java.awt.Color(255, 255, 255));
        privilegesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Privilegios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        privilegesPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        privilegesPanel.setName("privilegesPanel"); // NOI18N
        privilegesPanel.setOpaque(false);
        privilegesPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        privilegesPanel.setLayout(new javax.swing.BoxLayout(privilegesPanel, javax.swing.BoxLayout.Y_AXIS));

        privilegesFiller1.setName("privilegesFiller1"); // NOI18N
        privilegesPanel.add(privilegesFiller1);

        privilegePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar privilegio", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        privilegePanel.setName("privilegePanel"); // NOI18N
        privilegePanel.setOpaque(false);

        lblPrivilege.setText("Nombre");
        lblPrivilege.setName("lblPrivilege"); // NOI18N
        privilegePanel.add(lblPrivilege);

        txtPrivilege.setMinimumSize(new java.awt.Dimension(300, 30));
        txtPrivilege.setName("txtPrivilege"); // NOI18N
        txtPrivilege.setPreferredSize(new java.awt.Dimension(300, 30));
        txtPrivilege.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrivilegeKeyPressed(evt);
            }
        });
        privilegePanel.add(txtPrivilege);

        btnAddPrivilege.setText("Agregar");
        btnAddPrivilege.setName("btnAddPrivilege"); // NOI18N
        btnAddPrivilege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPrivilegeMouseClicked(evt);
            }
        });
        btnAddPrivilege.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddPrivilegeKeyPressed(evt);
            }
        });
        privilegePanel.add(btnAddPrivilege);

        privilegesPanel.add(privilegePanel);

        privilegesFiller2.setName("privilegesFiller2"); // NOI18N
        privilegesPanel.add(privilegesFiller2);

        existingPrivilegesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Privilegios existentes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        existingPrivilegesPanel.setName("existingPrivilegesPanel"); // NOI18N
        existingPrivilegesPanel.setOpaque(false);
        existingPrivilegesPanel.setLayout(new java.awt.GridBagLayout());

        existingPrivilegesScroll.setName("existingPrivilegesScroll"); // NOI18N

        existingPrivilegesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        existingPrivilegesList.setName("existingPrivilegesList"); // NOI18N
        existingPrivilegesScroll.setViewportView(existingPrivilegesList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        existingPrivilegesPanel.add(existingPrivilegesScroll, gridBagConstraints);

        btnModifyPrivilege.setText("Modificar");
        btnModifyPrivilege.setName("btnModifyPrivilege"); // NOI18N
        btnModifyPrivilege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyPrivilegeMouseClicked(evt);
            }
        });
        btnModifyPrivilege.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnModifyPrivilegeKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(btnModifyPrivilege, gridBagConstraints);

        btnDeletePrivilege.setText("Eliminar");
        btnDeletePrivilege.setName("btnDeletePrivilege"); // NOI18N
        btnDeletePrivilege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletePrivilegeMouseClicked(evt);
            }
        });
        btnDeletePrivilege.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeletePrivilegeKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(btnDeletePrivilege, gridBagConstraints);

        kindProductsCheck.setText("Tipos de productos");
        kindProductsCheck.setName("kindProductsCheck"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(kindProductsCheck, gridBagConstraints);

        departmentsCheck.setText("Departamentos");
        departmentsCheck.setName("departmentsCheck"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(departmentsCheck, gridBagConstraints);

        productsCheck.setText("Productos");
        productsCheck.setName("productsCheck"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(productsCheck, gridBagConstraints);

        employeesCheck.setText("Empleados");
        employeesCheck.setName("employeesCheck"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(employeesCheck, gridBagConstraints);

        hierarchiesCheck.setText("Jerarquías");
        hierarchiesCheck.setName("hierarchiesCheck"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(hierarchiesCheck, gridBagConstraints);

        privilegesCheck.setText("Privilegios");
        privilegesCheck.setName("privilegesCheck"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(privilegesCheck, gridBagConstraints);

        credentialsCheck.setText("Credenciales");
        credentialsCheck.setName("credentialsCheck"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(credentialsCheck, gridBagConstraints);

        accessesCheck.setText("Accesos");
        accessesCheck.setName("accessesCheck"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        existingPrivilegesPanel.add(accessesCheck, gridBagConstraints);

        privilegesPanel.add(existingPrivilegesPanel);

        privilegesFiller3.setName("privilegesFiller3"); // NOI18N
        privilegesPanel.add(privilegesFiller3);

        mainPanel.add(privilegesPanel, "privilegesPanel");

        accessesPanel.setBackground(new java.awt.Color(255, 255, 255));
        accessesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accesos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        accessesPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        accessesPanel.setName("accessesPanel"); // NOI18N
        accessesPanel.setOpaque(false);
        accessesPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.add(accessesPanel, "accessesPanel");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setMnemonic('A');
        fileMenu.setText("Archivo");
        fileMenu.setName("fileMenu"); // NOI18N

        exportItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/menubar/export.png"))); // NOI18N
        exportItem.setText("Exportar");
        exportItem.setName("exportItem"); // NOI18N
        exportItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportItemActionPerformed(evt);
            }
        });
        fileMenu.add(exportItem);

        printItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/menubar/print.png"))); // NOI18N
        printItem.setText("Imprimir");
        printItem.setName("printItem"); // NOI18N
        printItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printItemActionPerformed(evt);
            }
        });
        fileMenu.add(printItem);

        exitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/menubar/logout.png"))); // NOI18N
        exitItem.setText("Salir");
        exitItem.setName("exitItem"); // NOI18N
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('y');
        helpMenu.setText("Ayuda");
        helpMenu.setName("helpMenu"); // NOI18N

        aboutItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/over/resources/img/menubar/about.png"))); // NOI18N
        aboutItem.setText("Acerca de...");
        aboutItem.setName("aboutItem"); // NOI18N
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblKindProductLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKindProductLogoMouseClicked
        componentList = new ArrayList<>();
        componentList.add(txtKindProduct);
        componentList.add(btnAddKindProduct);
        componentList.add(existingKindProductsList);

        controller = new ProductKindController(componentList);
        ((ProductKindController)controller).refreshExistingProductsList();

        cardLayout.show(this.mainPanel, "kindProductsPanel");
    }//GEN-LAST:event_lblKindProductLogoMouseClicked

    private void lblProductLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductLogoMouseClicked
        cardLayout.show(this.mainPanel, "productsPanel");
    }//GEN-LAST:event_lblProductLogoMouseClicked

    private void lblCredentialsLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCredentialsLogoMouseClicked
        cardLayout.show(this.mainPanel, "credentialsPanel");
    }//GEN-LAST:event_lblCredentialsLogoMouseClicked

    private void lblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeesMouseClicked
        cardLayout.show(this.mainPanel, "employeesPanel");
    }//GEN-LAST:event_lblEmployeesMouseClicked

    private void lblDepartmentsLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDepartmentsLogoMouseClicked
        componentList = new ArrayList<>();
        componentList.add(txtDepartment);
        componentList.add(btnAddDepartment);
        componentList.add(btnModifyDepartment);
        componentList.add(btnDeleteDepartment);
        componentList.add(existingDepartmentsList);

        controller = new DepartmentController(componentList);
        ((DepartmentController)controller).refreshExistingDepartmentList();

        cardLayout.show(this.mainPanel, "departmentsPanel");
    }//GEN-LAST:event_lblDepartmentsLogoMouseClicked

    private void lblHierarchyLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHierarchyLogoMouseClicked
        componentList = new ArrayList<>();
        componentList.add(txtHierarchy);
        componentList.add(btnHierarchy);
        componentList.add(btnModifyHierarchy);
        componentList.add(btnDeleteHierarchy);
        componentList.add(existingHierarchiesTable);

        controller = new HierarchyController(componentList);
        ((HierarchyController)controller).refreshExistingHierarchiesTable();

        cardLayout.show(this.mainPanel, "hierarchiesPanel");
    }//GEN-LAST:event_lblHierarchyLogoMouseClicked

    private void lblPrivilegesLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrivilegesLogoMouseClicked
        componentList = new ArrayList<>();
        componentList.add(txtPrivilege);
        componentList.add(btnAddPrivilege);
        componentList.add(btnModifyPrivilege);
        componentList.add(btnDeletePrivilege);
        componentList.add(existingPrivilegesList);

        controller = new PrivilegeController(componentList);
        ((PrivilegeController)controller).refreshExistingPrivilegeList();

        cardLayout.show(this.mainPanel, "privilegesPanel");
    }//GEN-LAST:event_lblPrivilegesLogoMouseClicked

    private void lblAccessLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccessLogoMouseClicked
        cardLayout.show(this.mainPanel, "accessesPanel");
    }//GEN-LAST:event_lblAccessLogoMouseClicked

    private void exportItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportItemActionPerformed

    private void printItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_aboutItemActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        cardLayout.show(this.mainPanel, "dashboardPanel");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        cardLayout.show(this.mainPanel, Carousel.back(Carousel.getActivePanel(mainPanel)));        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        cardLayout.show(this.mainPanel, Carousel.next(Carousel.getActivePanel(mainPanel))); 
    }//GEN-LAST:event_btnNextActionPerformed

    private void txtKindProductKeyPressed(java.awt.event.KeyEvent evt) {
        controller.setFocus(evt);
    }

    private void btnAddKindProductKeyPressed(java.awt.event.KeyEvent evt) {
        controller.setFocus(evt);
    }

    private void existingKindProductsListKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void btnDeleteKindProductKeyPressed(java.awt.event.KeyEvent evt) {
        controller.setFocus(evt);
    }

    private void btnAddKindProductMouseClicked(java.awt.event.MouseEvent evt) {
        ((ProductKindController)controller).addKindOfProduct();
        ((ProductKindController)controller).refreshExistingProductsList();

        txtKindProduct.setText("");
        txtKindProduct.requestFocusInWindow();
    }

    private void btnModifyKindProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyProductMouseClicked
        ((ProductKindController)controller).updateKindOfProduct();
        ((ProductKindController)controller).refreshExistingProductsList();
    }

    private void btnDeleteKindProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteProductMouseClicked
        ((ProductKindController)controller).deleteKindOfProduct();
        ((ProductKindController)controller).refreshExistingProductsList();
    }

    private void btnModifyKindProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnModifyProductKeyPressed
        controller.setFocus(evt);
    }

    private void txtHierarchyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHierarchyKeyPressed
        controller.setFocus(evt);
    }//GEN-LAST:event_txtHierarchyKeyPressed

    private void btnHierarchyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHierarchyKeyPressed
        controller.setFocus(evt);
    }//GEN-LAST:event_btnHierarchyKeyPressed

    private void btnHierarchyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHierarchyMouseClicked
        ((HierarchyController)controller).addHierarchy();
        ((HierarchyController)controller).refreshExistingHierarchiesTable();

        txtHierarchy.setText("");
        txtHierarchy.requestFocusInWindow();
    }//GEN-LAST:event_btnHierarchyMouseClicked

    private void btnModifyHierarchyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnModifyHierarchyKeyPressed
        controller.setFocus(evt);
    }//GEN-LAST:event_btnModifyHierarchyKeyPressed

    private void btnModifyHierarchyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyHierarchyMouseClicked
        ((HierarchyController)controller).updateHierarchy();
        ((HierarchyController)controller).refreshExistingHierarchiesTable();
    }//GEN-LAST:event_btnModifyHierarchyMouseClicked

    private void btnDeleteHierarchyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeleteHierarchyKeyPressed
        controller.setFocus(evt);
    }//GEN-LAST:event_btnDeleteHierarchyKeyPressed

    private void btnDeleteHierarchyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteHierarchyMouseClicked
        ((HierarchyController)controller).deleteHierarchy();
        ((HierarchyController)controller).refreshExistingHierarchiesTable();
    }//GEN-LAST:event_btnDeleteHierarchyMouseClicked

    private void txtPrivilegeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrivilegeKeyPressed
        controller.setFocus(evt);
    }//GEN-LAST:event_txtPrivilegeKeyPressed

    private void btnAddPrivilegeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddPrivilegeKeyPressed
        controller.setFocus(evt);
    }//GEN-LAST:event_btnAddPrivilegeKeyPressed

    private void btnAddPrivilegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPrivilegeMouseClicked
        ((PrivilegeController)controller).addPrivilege();
        ((PrivilegeController)controller).refreshExistingPrivilegeList();

        txtPrivilege.setText("");
        txtPrivilege.requestFocusInWindow();
    }//GEN-LAST:event_btnAddPrivilegeMouseClicked

    private void btnModifyPrivilegeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnModifyPrivilegeKeyPressed
        controller.setFocus(evt);
    }//GEN-LAST:event_btnModifyPrivilegeKeyPressed

    private void btnModifyPrivilegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyPrivilegeMouseClicked
        ((PrivilegeController)controller).updatePrivilege();
        ((PrivilegeController)controller).refreshExistingPrivilegeList();
    }//GEN-LAST:event_btnModifyPrivilegeMouseClicked

    private void btnDeletePrivilegeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeletePrivilegeKeyPressed
        controller.setFocus(evt);
    }//GEN-LAST:event_btnDeletePrivilegeKeyPressed

    private void btnDeletePrivilegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePrivilegeMouseClicked
        ((PrivilegeController)controller).deletePrivilege();
        ((PrivilegeController)controller).refreshExistingPrivilegeList();
    }//GEN-LAST:event_btnDeletePrivilegeMouseClicked

    private void btnAddDepartmentKeyPressed(java.awt.event.KeyEvent evt) {
        controller.setFocus(evt);
    }

    private void btnAddDepartmentMouseClicked(java.awt.event.MouseEvent evt) {
        ((DepartmentController)controller).addDepartment();
        ((DepartmentController)controller).refreshExistingDepartmentList();

        txtDepartment.setText("");
        txtDepartment.requestFocusInWindow();
    }

    private void btnModifyDepartmentKeyPressed(java.awt.event.KeyEvent evt) {
        controller.setFocus(evt);
    }

    private void btnModifyDepartmentMouseClicked(java.awt.event.MouseEvent evt) {
        ((DepartmentController)controller).updateDepartment();
        ((DepartmentController)controller).refreshExistingDepartmentList();
    }

    private void btnDeleteDepartmentKeyPressed(java.awt.event.KeyEvent evt) {
        controller.setFocus(evt);
    }

    private void btnDeleteDepartmentMouseClicked(java.awt.event.MouseEvent evt) {
        ((DepartmentController)controller).deleteDepartment();
        ((DepartmentController)controller).refreshExistingDepartmentList();
    }

    private void btnAddProductKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAddProductMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JCheckBox accessesCheck;
    private javax.swing.JPanel accessesPanel;
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnAddKindProduct;
    private javax.swing.JButton btnAddPrivilege;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteDepartment;
    private javax.swing.JButton btnDeleteHierarchy;
    private javax.swing.JButton btnDeleteKindProduct;
    private javax.swing.JButton btnDeletePrivilege;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnHierarchy;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnModifyDepartment;
    private javax.swing.JButton btnModifyHierarchy;
    private javax.swing.JButton btnModifyKindProduct;
    private javax.swing.JButton btnModifyPrivilege;
    private javax.swing.JButton btnModifyProduct;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cmbKindProduct;
    private javax.swing.JCheckBox credentialsCheck;
    private javax.swing.JPanel credentialsPanel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel departmentPanel;
    private javax.swing.JCheckBox departmentsCheck;
    private javax.swing.Box.Filler departmentsFiller1;
    private javax.swing.Box.Filler departmentsFiller2;
    private javax.swing.Box.Filler departmentsFiller3;
    private javax.swing.JPanel departmentsPanel;
    private javax.swing.JCheckBox employeesCheck;
    private javax.swing.JList<String> existingDepartmentsList;
    private javax.swing.JPanel existingDepartmentsPanel;
    private javax.swing.JScrollPane existingDepartmentsScroll;
    private javax.swing.JPanel existingHierarchiesPanel;
    private javax.swing.JScrollPane existingHierarchiesScroll;
    private javax.swing.JTable existingHierarchiesTable;
    private javax.swing.JList<String> existingKindProductsList;
    private javax.swing.JPanel existingKindProductsPanel;
    private javax.swing.JScrollPane existingKindProductsScroll;
    private javax.swing.JList<String> existingPrivilegesList;
    private javax.swing.JPanel existingPrivilegesPanel;
    private javax.swing.JScrollPane existingPrivilegesScroll;
    private javax.swing.JPanel existingProductsPanel;
    private javax.swing.JScrollPane existingProductsScroll;
    private javax.swing.JTable existingProductsTable;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JPanel exployeesPanel;
    private javax.swing.JMenuItem exportItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JCheckBox hierarchiesCheck;
    private javax.swing.Box.Filler hierarchiesFiller1;
    private javax.swing.Box.Filler hierarchiesFiller2;
    private javax.swing.Box.Filler hierarchiesFiller3;
    private javax.swing.JPanel hierarchiesPanel;
    private javax.swing.JPanel hierarchyPanel;
    private javax.swing.JPanel kindProductPanel;
    private javax.swing.JCheckBox kindProductsCheck;
    private javax.swing.JPanel kindProductsPanel;
    private javax.swing.JLabel lblAccessLogo;
    private javax.swing.JLabel lblCredentialsLogo;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartmentsLogo;
    private javax.swing.JLabel lblEmployees;
    private javax.swing.JLabel lblHierarchy;
    private javax.swing.JLabel lblHierarchyLogo;
    private javax.swing.JLabel lblKind;
    private javax.swing.JLabel lblKindProduct;
    private javax.swing.JLabel lblKindProductLogo;
    private javax.swing.JLabel lblPrivilege;
    private javax.swing.JLabel lblPrivilegesLogo;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProductLogo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem printItem;
    private javax.swing.JPanel privilegePanel;
    private javax.swing.JCheckBox privilegesCheck;
    private javax.swing.Box.Filler privilegesFiller1;
    private javax.swing.Box.Filler privilegesFiller2;
    private javax.swing.Box.Filler privilegesFiller3;
    private javax.swing.JPanel privilegesPanel;
    private javax.swing.Box.Filler productFiller1;
    private javax.swing.Box.Filler productFiller2;
    private javax.swing.Box.Filler productFiller3;
    private javax.swing.JPanel productPanel;
    private javax.swing.JCheckBox productsCheck;
    private javax.swing.Box.Filler productsFiller1;
    private javax.swing.Box.Filler productsFiller2;
    private javax.swing.Box.Filler productsFiller3;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JToolBar.Separator separator;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtHierarchy;
    private javax.swing.JTextField txtKindProduct;
    private javax.swing.JTextField txtPrivilege;
    private javax.swing.JTextField txtProduct;
    // End of variables declaration//GEN-END:variables
}